<a href="https://colab.research.google.com/github/gauravtailor8520/Machine-Learning/blob/main/multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Sklearn

In [ ]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [ ]:
X

array([[-1.16832715e+00, -8.75464789e-01],
       [-7.32226936e-01,  1.61056421e+00],
       [ 7.07634914e-01, -1.45350980e+00],
       [-1.40540369e+00,  1.13755325e+00],
       [ 1.29122190e-01,  6.95598840e-01],
       [ 5.27987919e-01, -7.91597305e-02],
       [ 1.10021187e+00,  1.60171975e+00],
       [ 5.41646236e-01, -1.38042579e+00],
       [ 1.40691875e+00,  7.54441462e-01],
       [-1.29086789e+00, -1.50212787e+00],
       [ 1.18293018e-01,  4.08595766e-01],
       [ 1.10955908e+00, -1.12331072e+00],
       [ 2.03393608e+00,  6.08184694e-01],
       [-5.47858263e-01, -7.15396281e-01],
       [-1.90016776e+00,  1.24650320e+00],
       [ 2.01272009e+00,  2.07799039e-01],
       [ 5.19370954e-02, -1.31674664e+00],
       [-4.92224873e-01,  2.62923139e-01],
       [ 2.49618606e-01,  1.12201854e+00],
       [ 1.98664760e-01,  1.13323112e+00],
       [-4.20002220e-01, -1.08879335e+00],
       [ 1.13249728e-01, -3.39300065e-01],
       [-2.93101287e-01, -6.64211704e-01],
       [-1.

In [ ]:
y

array([ -98.91678023,  -11.70861783,   59.33656318,   46.87206904,
        115.25331384,   26.85388313,   92.19828023,  -57.78163608,
        167.33528308, -108.3930598 , -101.18754065,   33.84428872,
        145.37244625,  -66.16470806,  -85.25890042,   75.13687086,
       -100.91317222,  -89.9766255 ,   63.39273544,  118.03583905,
        -21.9774145 ,   18.36235667,  -78.83621124,    1.53260975,
          2.04536123,   21.1353281 ,   32.19206611,  120.88184896,
       -122.01044148,   29.5310267 ,   13.60242031, -103.9192829 ,
         48.29242274,   94.05334037,   32.95806499,    0.68084652,
         50.68866818,   24.5953839 ,   72.61283683,  -41.87332453,
         77.61443144,  -87.24305208,  -30.25708767,  203.69854501,
         23.90940796,  132.78492451,  -37.72868155,  -46.49730882,
         33.74918917,  128.11384252,   88.48670486,   76.05234353,
        -15.96283825,  101.00089796,  -19.71018195,   26.47194386,
         47.1272148 ,  139.93371814,   49.45314368,  -58.24069

In [ ]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [ ]:
df.shape

(100, 3)

In [ ]:
df.head()

feature1  feature2      target
0 -1.168327 -0.875465  -98.916780
1 -0.732227  1.610564  -11.708618
2  0.707635 -1.453510   59.336563
3 -1.405404  1.137553   46.872069
4  0.129122  0.695599  115.253314

In [ ]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.show()

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
lr.coef_

array([41.19436195, 35.66773662])

In [ ]:
lr.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

In [ ]:
lr.score(X_train,y_train)

0.5227261163667374

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 30.416060704139845
MSE 1446.7830818016048
R2 score 0.6740433275875786


In [ ]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T
z = lr.predict(final).reshape(10,10)





In [ ]:
x

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [ ]:
xGrid

array([[-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778

In [ ]:
xGrid.ravel()

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ,
       -5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ,
       -5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ,
       -5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ,
       -5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ,
       -5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ,
       -5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.  

In [ ]:
xGrid.ravel().reshape(1,100)

array([[-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ,
        -5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ,
        -5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ,
        -5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ,
        -5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ,
        -5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ,
        -5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.8

In [ ]:
final

array([[-5.        , -5.        ],
       [-3.88888889, -5.        ],
       [-2.77777778, -5.        ],
       [-1.66666667, -5.        ],
       [-0.55555556, -5.        ],
       [ 0.55555556, -5.        ],
       [ 1.66666667, -5.        ],
       [ 2.77777778, -5.        ],
       [ 3.88888889, -5.        ],
       [ 5.        , -5.        ],
       [-5.        , -3.88888889],
       [-3.88888889, -3.88888889],
       [-2.77777778, -3.88888889],
       [-1.66666667, -3.88888889],
       [-0.55555556, -3.88888889],
       [ 0.55555556, -3.88888889],
       [ 1.66666667, -3.88888889],
       [ 2.77777778, -3.88888889],
       [ 3.88888889, -3.88888889],
       [ 5.        , -3.88888889],
       [-5.        , -2.77777778],
       [-3.88888889, -2.77777778],
       [-2.77777778, -2.77777778],
       [-1.66666667, -2.77777778],
       [-0.55555556, -2.77777778],
       [ 0.55555556, -2.77777778],
       [ 1.66666667, -2.77777778],
       [ 2.77777778, -2.77777778],
       [ 3.88888889,

In [ ]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [ ]:
lr.coef_

array([41.19436195, 35.66773662])

In [ ]:
lr.intercept_

4.892221542031997

# Code From Scretch

In [ ]:
import numpy as np
from sklearn.datasets import load_diabetes

In [ ]:
X,y = load_diabetes(return_X_y=True)

In [ ]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [ ]:
X.shape

(442, 10)

In [ ]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [ ]:
y.shape

(442,)

## Using Sklearn's Linear Regression

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
reg = LinearRegression()

In [ ]:
reg.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred = reg.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test,y_pred)

0.4399338661568968

In [ ]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [ ]:
reg.intercept_

151.88331005254167

## Making our own Linear Regression Class

In [ ]:
class MeraLR:

    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)

        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred



In [ ]:
lr = MeraLR()

In [ ]:
lr.fit(X_train,y_train)

In [ ]:
X_train.shape

(353, 10)

In [ ]:
np.insert(X_train,0,1,axis=1).shape

(353, 11)

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
r2_score(y_test,y_pred)

0.43993386615689634

In [ ]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [ ]:
lr.intercept_

151.88331005254165